print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")
print("Hello, World!")
print("WWWWWWWWWW")